addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.4.3")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"            % "0.11.0")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"            % "1.9.0")
addSbtPlugin("org.scalameta"      % "sbt-mdoc"                 % "2.2.23")
addSbtPlugin("ch.epfl.scala"      % "sbt-bloop"                % "1.4.10")
addSbtPlugin("com.eed3si9n"       % "sbt-unidoc"               % "0.4.3")
addSbtPlugin("com.geirsson"       % "sbt-ci-release"           % "1.5.7")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.8.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.1.0")
addSbtPlugin("io.spray"           % "sbt-revolver"             % "0.9.1")
addSbtPlugin("dev.zio"            % "zio-sbt-website"          % "0.1.5+28-4b5b0374-SNAPSHOT")

resolvers += Resolver.sonatypeRepo("public")
